# SITE CONFIGURATION
title: Roszak Fliesen & Trockenbau   # your site title
author: mi711cz # You :P
description: > # Meta description of Homepage
  Roszak Fliesen & Trockenbau der Beste der Besten Trockenbauer.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://roszak-fliesen-trockenbau.de" # the base hostname & protocol for your site, e.g. http://example.com


# SEO PLUGIN
#social:
#  name: Your Name
#  links:
#    - https://www.facebook.com/ben.balter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Über Uns', link: '/about'}
  - {name: 'Kontakt', link: '/contact'}
  - {name: 'Impressum', link: '/impressum'}

tagline: >
  Ihr freundlicher und professioneller Partner rund um Fliesen und Trockenbau

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: bogdan.roszak13@gmail.com # email for form submission

#twitter_username: exampleUserName # replace with your_twitter_username or comment to remove link from footer
#github_username:  exampleUserName # replace with your_github_username or comment to remove link from footer
#instagram_username: exampleUserName # replace with your_instagram_username or comment to remove link from footer

#disqus:
#  shortname: exampleUserName # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
